[package]
name = "metad-reweight"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
csv = "1.3.0"
ndarray = "0.15.6"
polars = { version = "0.41.3", features = ["lazy"] }
